"""document and chunk, with a real vector column and the effectivity indexes

Revision ID: 0001
Revises:
Create Date: 2026-09-24

Written by hand rather than autogenerated. Autogenerate emits `CREATE EXTENSION` never, an HNSW
index as a btree, and a `Vector(384)` column as whatever the dialect reflects — all three are the
parts of this schema that kill condition K is about, so all three are stated explicitly here.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

from parts_answer_gate.retrieval.embeddings import EMBEDDING_DIM
from parts_answer_gate.store.schema import HNSW_BUILD_PARAMETERS

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # First statement of the first migration: every later object in this file depends on it, and a
    # database without it fails at `CREATE TABLE` rather than at query time, which is the error
    # message a developer can act on.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "document",
        sa.Column("document_id", sa.String(64), primary_key=True),
        sa.Column("family_id", sa.String(64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("language", sa.String(2), nullable=False),
        sa.Column("revision", sa.String(32), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        # No foreign key: a supersession edge points at a revision that is often loaded afterwards.
        sa.Column("superseded_by", sa.String(64), nullable=True),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(64), nullable=False),
    )
    op.create_index("ix_document_family", "document", ["family_id"])
    op.create_index("ix_document_in_force", "document", ["valid_from", "valid_to"])

    op.create_table(
        "chunk",
        sa.Column("chunk_id", sa.String(64), primary_key=True),
        sa.Column(
            "document_id",
            sa.String(64),
            sa.ForeignKey("document.document_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("family_id", sa.String(64), nullable=False),
        sa.Column("language", sa.String(2), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("section", sa.String(64), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.String(64), nullable=False),
        sa.Column("serial_first", sa.Integer(), nullable=True),
        sa.Column("serial_last", sa.Integer(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("superseded_by", sa.String(64), nullable=True),
        sa.Column(
            "identifiers",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
        sa.Column("content_hash", sa.String(32), nullable=False),
        sa.Column("content_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column("embedding_model", sa.String(128), nullable=True),
        sa.Column("embedded_at", sa.DateTime(timezone=True), nullable=True),
    )

    # The effectivity predicate. Variant first because it is the selective term; the date columns
    # follow so a query naming a machine and a date is answered from one index.
    op.create_index("ix_chunk_effectivity", "chunk", ["variant_id", "valid_from", "valid_to"])
    op.create_index("ix_chunk_in_force", "chunk", ["valid_from", "valid_to"])
    # GIN: the deterministic lookup is an array-overlap test, which no btree can serve.
    op.create_index("ix_chunk_identifiers", "chunk", ["identifiers"], postgresql_using="gin")
    op.create_index("ix_chunk_document", "chunk", ["document_id"])
    op.create_index("ix_chunk_family_language", "chunk", ["family_id", "language"])

    op.create_index(
        str(HNSW_BUILD_PARAMETERS["index_name"]),
        "chunk",
        ["embedding"],
        postgresql_using=str(HNSW_BUILD_PARAMETERS["method"]),
        postgresql_with={
            "m": HNSW_BUILD_PARAMETERS["m"],
            "ef_construction": HNSW_BUILD_PARAMETERS["ef_construction"],
        },
        postgresql_ops={"embedding": str(HNSW_BUILD_PARAMETERS["opclass"])},
    )


def downgrade() -> None:
    op.drop_table("chunk")
    op.drop_table("document")
    # The extension is left in place. Dropping it would remove the type from any other schema in the
    # same database, and a downgrade is not a licence to break a neighbour.
